### PR TITLE
Adding arguments for some hardcoded defaults

### PR DESCRIPTION
**Pull request by linsomniac**
To achieve this, I restructured the option handling code, which
involved restructuring the initialization code.  Over all, this
should do the same thing but the code should be more clear, with
fewer repetitions when modifying the option handling code in the
future.  Over all, the code is shorter and more clear.

Added arguments for SINGLEPART_UPLOAD_MAX, SINGLEPART_DOWNLOAD_MAX, DEFAULT_SPLIT, and RETRY_DELAY.

### CODE REVIEW

**Comment by oniltonmaciel** [comment]
+1  on this.

This would be very helpful to me.

It seems no code was commited this year (2015) yet and none was commited since September of 2014. 

Is this repo abandoned?

**Comment by chouhanyang** [comment]
Not particularly. I'm just trying to merge multiple pull requests as they have some conflicts. Also need to run regression tests to make sure nothing broken.

**Comment by linsomniac** [comment]
At the time I submitted this patch, it applied cleanly to the repo.  But it did change a lot of the structure of the code, so not adopting it at that time has probably lead to other pull requests being incompatible with these changes.

I know that because this change involved so much restructuring that it was not as easy to just apply and be done with as the others I submitted around that time.  If you are interested in taking this pull request, but don't want it to interfere with the others, go ahead and accept those that you want, and then let me know and I'll re-work this patch to apply on top of those.

If you would then take this patch, it's work I'd be willing to do.  Otherwise, just close this and move on.  I think the changes in here are worthwhile, and they were significant work because of the restructuring, but you make the call you are happy with.

**Comment by chouhanyang** [comment]
Sure, I think your clean up is valuable. I just merged #21, so wondering if you would like to help update your pull request so I can merge your change again if you think it is still necessary?

I can do a regression test for each merge BTW. Thank you.

**Comment by linsomniac** [comment]
Yes, let me get this one work task done and then I'll update the pull request.

**Comment by linsomniac** [comment]
I've created a new pull request with these change in it, based on trunk.

**Pull request closed without merging**
