### PR TITLE
Add --ignore-certificate to not to verify the ssl certificate.

### PR DESCRIPTION
**Pull request by MISSEY**
This would solve the issue when there is custom s3 deployed such as own house minio installation.

### CODE REVIEW

**Comment by MISSEY** [comment]
@debodirno @rozuur @navinpai Could you please review this pull request, as it would solve the problem of inhouse deployment of S3.

**Comment by Woytek-Polnik** [comment]
Could we have it reviewed? 🙏

**Review by debodirno — APPROVED** [review]
Looks good to me!

**Comment by debodirno** [comment]
@yashgupta9696 - could you please test and get this merged?

**Comment by yashgupta9696** [comment]
LGTM!

**Review by yashgupta9696 — APPROVED** [review]

**Pull request merged**
