### PR TITLE
Port of Adding arguments for some hardcoded defaults.

### PR DESCRIPTION
**Pull request by linsomniac**
This is a port of my previous set arguments changes to the new trunk.  This should apply cleanly now.

### CODE REVIEW

**Comment by linsomniac** [comment]
I've patched the above traceback.  As far as your question about keeping the Options class, the bulk of this patch is about removing the Options class since it is code that is duplicated by the argument parser.  If you want options back in there, just drop this patch.

However, the Options class is not a very typical API for for use as a Python library.  If you want to go that route, you should probably restructure S3Handler to take named arguments in the __init__ and have a wrapper that takes the options and passes them as arguments there, and probably restructure the S3Handler and CommandHandler so that they aren't separate but unrelated classes.

**Comment by chouhanyang** [comment]
A typical usage from our code is like this:

        opt = Options()
        opt.recursive = True
        S3Handler(opt).del_files(output_path)

So another option is to keep a dummy Option class as container. Do you think there is a way to get default values directly from OptionParser?

I like your implementation, but on the other hand, I would like to keep the backward compatibility just in case people rely on it. :)

**Comment by linsomniac** [comment]
The parser includes an attribute called "option_list" which is a list of the option objects.  You can get access to the "dest" name and the default with:

    for o in parser.option_list:
        print o.dest, o.default

**Comment by chouhanyang** [comment]
Thank you. Here is the output:

None ('NO', 'DEFAULT')
s3cfg None
force False
recursive False
sync_check False
dry_run False
retry 3
retry_delay 10
num_threads 16
show_dir False
ignore_empty_source False
use_ssl False
verbose False
debug False
validate ('NO', 'DEFAULT')
delete_removed ('NO', 'DEFAULT')
multipart_split_size 52428800
max_singlepart_download_size 52428800
max_singlepart_upload_size 4718592000

I think you missed the default value for "validate" & "delete_removed" in your change?

Also, in this case, can you refactor the initialization of the parser, and use parser.option_list for the initialization of dummy Option class, which would be a clear so we can keep the Option class available?

Your change passed all regression tests BTW.

**Comment by chouhanyang** [comment]
Just some quick idea like:

class Options:
  '''Default option class for available options. Use the default value from opt parser.
     The values can be overwritten by command line options or set at run-time.
  '''
  def __init__(self, opt = None):
    parser = get_opt_parser()
    for o in parser.option_list:
      self.__dict__[o.dest] = o.default if (opt is None) or (opt.__dict__[o.dest] is None) else opt.__dict__[o.dest]

Hope this helps.

**Comment by chouhanyang** [comment]
Hi linsomniac,

Not seeing your response for a while. At this point, I'll just go ahead and merge your change, then apply my fixed on top of it, if that's okay with you?

**Comment by linsomniac** [comment]
Yep, sorry, been super busy...  Buying a house and stuff. Sorry about that.

**Comment by chouhanyang** [comment]
Ah, best wishes on your new house. I will merge your change today or tomorrow. Thanks!

**Pull request merged**
